// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: pkg/proto/ApiSyncService.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TTSService_UploadAudio_FullMethodName = "/apisyniq.TTSService/UploadAudio"
	TTSService_UploadText_FullMethodName  = "/apisyniq.TTSService/UploadText"
	TTSService_UploadEvent_FullMethodName = "/apisyniq.TTSService/UploadEvent"
	TTSService_UploadError_FullMethodName = "/apisyniq.TTSService/UploadError"
)

// TTSServiceClient is the client API for TTSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TTSServiceClient interface {
	UploadAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamPacket, Empty], error)
	UploadText(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Text, Empty], error)
	UploadEvent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, Empty], error)
	UploadError(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Error, Empty], error)
}

type tTSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTTSServiceClient(cc grpc.ClientConnInterface) TTSServiceClient {
	return &tTSServiceClient{cc}
}

func (c *tTSServiceClient) UploadAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamPacket, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSService_ServiceDesc.Streams[0], TTSService_UploadAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPacket, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_UploadAudioClient = grpc.ClientStreamingClient[StreamPacket, Empty]

func (c *tTSServiceClient) UploadText(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Text, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSService_ServiceDesc.Streams[1], TTSService_UploadText_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Text, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_UploadTextClient = grpc.ClientStreamingClient[Text, Empty]

func (c *tTSServiceClient) UploadEvent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSService_ServiceDesc.Streams[2], TTSService_UploadEvent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_UploadEventClient = grpc.ClientStreamingClient[Event, Empty]

func (c *tTSServiceClient) UploadError(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Error, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSService_ServiceDesc.Streams[3], TTSService_UploadError_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Error, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_UploadErrorClient = grpc.ClientStreamingClient[Error, Empty]

// TTSServiceServer is the server API for TTSService service.
// All implementations must embed UnimplementedTTSServiceServer
// for forward compatibility.
type TTSServiceServer interface {
	UploadAudio(grpc.ClientStreamingServer[StreamPacket, Empty]) error
	UploadText(grpc.ClientStreamingServer[Text, Empty]) error
	UploadEvent(grpc.ClientStreamingServer[Event, Empty]) error
	UploadError(grpc.ClientStreamingServer[Error, Empty]) error
	mustEmbedUnimplementedTTSServiceServer()
}

// UnimplementedTTSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTTSServiceServer struct{}

func (UnimplementedTTSServiceServer) UploadAudio(grpc.ClientStreamingServer[StreamPacket, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method UploadAudio not implemented")
}
func (UnimplementedTTSServiceServer) UploadText(grpc.ClientStreamingServer[Text, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method UploadText not implemented")
}
func (UnimplementedTTSServiceServer) UploadEvent(grpc.ClientStreamingServer[Event, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method UploadEvent not implemented")
}
func (UnimplementedTTSServiceServer) UploadError(grpc.ClientStreamingServer[Error, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method UploadError not implemented")
}
func (UnimplementedTTSServiceServer) mustEmbedUnimplementedTTSServiceServer() {}
func (UnimplementedTTSServiceServer) testEmbeddedByValue()                    {}

// UnsafeTTSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TTSServiceServer will
// result in compilation errors.
type UnsafeTTSServiceServer interface {
	mustEmbedUnimplementedTTSServiceServer()
}

func RegisterTTSServiceServer(s grpc.ServiceRegistrar, srv TTSServiceServer) {
	// If the following call pancis, it indicates UnimplementedTTSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TTSService_ServiceDesc, srv)
}

func _TTSService_UploadAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TTSServiceServer).UploadAudio(&grpc.GenericServerStream[StreamPacket, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_UploadAudioServer = grpc.ClientStreamingServer[StreamPacket, Empty]

func _TTSService_UploadText_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TTSServiceServer).UploadText(&grpc.GenericServerStream[Text, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_UploadTextServer = grpc.ClientStreamingServer[Text, Empty]

func _TTSService_UploadEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TTSServiceServer).UploadEvent(&grpc.GenericServerStream[Event, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_UploadEventServer = grpc.ClientStreamingServer[Event, Empty]

func _TTSService_UploadError_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TTSServiceServer).UploadError(&grpc.GenericServerStream[Error, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_UploadErrorServer = grpc.ClientStreamingServer[Error, Empty]

// TTSService_ServiceDesc is the grpc.ServiceDesc for TTSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TTSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apisyniq.TTSService",
	HandlerType: (*TTSServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadAudio",
			Handler:       _TTSService_UploadAudio_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadText",
			Handler:       _TTSService_UploadText_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadEvent",
			Handler:       _TTSService_UploadEvent_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadError",
			Handler:       _TTSService_UploadError_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/ApiSyncService.proto",
}
