// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/proto/ApiSyncService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioBytes    []byte                 `protobuf:"bytes,1,opt,name=audio_bytes,json=audioBytes,proto3" json:"audio_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawAudio) Reset() {
	*x = RawAudio{}
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawAudio) ProtoMessage() {}

func (x *RawAudio) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawAudio.ProtoReflect.Descriptor instead.
func (*RawAudio) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ApiSyncService_proto_rawDescGZIP(), []int{0}
}

func (x *RawAudio) GetAudioBytes() []byte {
	if x != nil {
		return x.AudioBytes
	}
	return nil
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioBytes    []byte                 `protobuf:"bytes,1,opt,name=audio_bytes,json=audioBytes,proto3" json:"audio_bytes,omitempty"`
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      int32                  `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,7,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Language      string                 `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`
	AudioOption   string                 `protobuf:"bytes,9,opt,name=audio_option,json=audioOption,proto3" json:"audio_option,omitempty"`
	Options       map[string]string      `protobuf:"bytes,10,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ApiSyncService_proto_rawDescGZIP(), []int{1}
}

func (x *AudioChunk) GetAudioBytes() []byte {
	if x != nil {
		return x.AudioBytes
	}
	return nil
}

func (x *AudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioChunk) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AudioChunk) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AudioChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AudioChunk) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AudioChunk) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AudioChunk) GetAudioOption() string {
	if x != nil {
		return x.AudioOption
	}
	return ""
}

func (x *AudioChunk) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type IncomingAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioChunk    []byte                 `protobuf:"bytes,1,opt,name=audio_chunk,json=audioChunk,proto3" json:"audio_chunk,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	AudioOption   string                 `protobuf:"bytes,6,opt,name=audio_option,json=audioOption,proto3" json:"audio_option,omitempty"`
	Options       map[string]string      `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingAudio) Reset() {
	*x = IncomingAudio{}
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingAudio) ProtoMessage() {}

func (x *IncomingAudio) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingAudio.ProtoReflect.Descriptor instead.
func (*IncomingAudio) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ApiSyncService_proto_rawDescGZIP(), []int{2}
}

func (x *IncomingAudio) GetAudioChunk() []byte {
	if x != nil {
		return x.AudioChunk
	}
	return nil
}

func (x *IncomingAudio) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *IncomingAudio) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IncomingAudio) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *IncomingAudio) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *IncomingAudio) GetAudioOption() string {
	if x != nil {
		return x.AudioOption
	}
	return ""
}

func (x *IncomingAudio) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Options       map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ApiSyncService_proto_rawDescGZIP(), []int{3}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Text) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Text) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Text) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Text) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Text) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Options       map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ApiSyncService_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Event) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Event) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Event) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Options       map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ApiSyncService_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Error) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Error) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Error) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *Error) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Error) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type StreamPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Packet:
	//
	//	*StreamPacket_AudioIn
	//	*StreamPacket_AudioOut
	//	*StreamPacket_Text
	//	*StreamPacket_Event
	//	*StreamPacket_Error
	//	*StreamPacket_RawAudio
	Packet        isStreamPacket_Packet `protobuf_oneof:"packet"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPacket) Reset() {
	*x = StreamPacket{}
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPacket) ProtoMessage() {}

func (x *StreamPacket) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPacket.ProtoReflect.Descriptor instead.
func (*StreamPacket) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ApiSyncService_proto_rawDescGZIP(), []int{6}
}

func (x *StreamPacket) GetPacket() isStreamPacket_Packet {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *StreamPacket) GetAudioIn() *IncomingAudio {
	if x != nil {
		if x, ok := x.Packet.(*StreamPacket_AudioIn); ok {
			return x.AudioIn
		}
	}
	return nil
}

func (x *StreamPacket) GetAudioOut() *AudioChunk {
	if x != nil {
		if x, ok := x.Packet.(*StreamPacket_AudioOut); ok {
			return x.AudioOut
		}
	}
	return nil
}

func (x *StreamPacket) GetText() *Text {
	if x != nil {
		if x, ok := x.Packet.(*StreamPacket_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *StreamPacket) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Packet.(*StreamPacket_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *StreamPacket) GetError() *Error {
	if x != nil {
		if x, ok := x.Packet.(*StreamPacket_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *StreamPacket) GetRawAudio() *RawAudio {
	if x != nil {
		if x, ok := x.Packet.(*StreamPacket_RawAudio); ok {
			return x.RawAudio
		}
	}
	return nil
}

type isStreamPacket_Packet interface {
	isStreamPacket_Packet()
}

type StreamPacket_AudioIn struct {
	AudioIn *IncomingAudio `protobuf:"bytes,1,opt,name=audio_in,json=audioIn,proto3,oneof"`
}

type StreamPacket_AudioOut struct {
	AudioOut *AudioChunk `protobuf:"bytes,2,opt,name=audio_out,json=audioOut,proto3,oneof"`
}

type StreamPacket_Text struct {
	Text *Text `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type StreamPacket_Event struct {
	Event *Event `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

type StreamPacket_Error struct {
	Error *Error `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type StreamPacket_RawAudio struct {
	RawAudio *RawAudio `protobuf:"bytes,6,opt,name=raw_audio,json=rawAudio,proto3,oneof"`
}

func (*StreamPacket_AudioIn) isStreamPacket_Packet() {}

func (*StreamPacket_AudioOut) isStreamPacket_Packet() {}

func (*StreamPacket_Text) isStreamPacket_Packet() {}

func (*StreamPacket_Event) isStreamPacket_Packet() {}

func (*StreamPacket_Error) isStreamPacket_Packet() {}

func (*StreamPacket_RawAudio) isStreamPacket_Packet() {}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ApiSyncService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ApiSyncService_proto_rawDescGZIP(), []int{7}
}

var File_pkg_proto_ApiSyncService_proto protoreflect.FileDescriptor

const file_pkg_proto_ApiSyncService_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/proto/ApiSyncService.proto\x12\bapisyniq\"+\n" +
	"\bRawAudio\x12\x1f\n" +
	"\vaudio_bytes\x18\x01 \x01(\fR\n" +
	"audioBytes\"\x8e\x03\n" +
	"\n" +
	"AudioChunk\x12\x1f\n" +
	"\vaudio_bytes\x18\x01 \x01(\fR\n" +
	"audioBytes\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\x05R\bchannels\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\a \x01(\tR\bstreamId\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\x12!\n" +
	"\faudio_option\x18\t \x01(\tR\vaudioOption\x12;\n" +
	"\aoptions\x18\n" +
	" \x03(\v2!.apisyniq.AudioChunk.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x02\n" +
	"\rIncomingAudio\x12\x1f\n" +
	"\vaudio_chunk\x18\x01 \x01(\fR\n" +
	"audioChunk\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\tR\bstreamId\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12!\n" +
	"\faudio_option\x18\x06 \x01(\tR\vaudioOption\x12>\n" +
	"\aoptions\x18\a \x03(\v2$.apisyniq.IncomingAudio.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x02\n" +
	"\x04Text\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\tR\bstreamId\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x125\n" +
	"\aoptions\x18\x06 \x03(\v2\x1b.apisyniq.Text.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x02\n" +
	"\x05Event\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\tR\bstreamId\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x126\n" +
	"\aoptions\x18\x06 \x03(\v2\x1c.apisyniq.Event.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x02\n" +
	"\x05Error\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\tR\bstreamId\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x126\n" +
	"\aoptions\x18\x06 \x03(\v2\x1c.apisyniq.Error.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x02\n" +
	"\fStreamPacket\x124\n" +
	"\baudio_in\x18\x01 \x01(\v2\x17.apisyniq.IncomingAudioH\x00R\aaudioIn\x123\n" +
	"\taudio_out\x18\x02 \x01(\v2\x14.apisyniq.AudioChunkH\x00R\baudioOut\x12$\n" +
	"\x04text\x18\x03 \x01(\v2\x0e.apisyniq.TextH\x00R\x04text\x12'\n" +
	"\x05event\x18\x04 \x01(\v2\x0f.apisyniq.EventH\x00R\x05event\x12'\n" +
	"\x05error\x18\x05 \x01(\v2\x0f.apisyniq.ErrorH\x00R\x05error\x121\n" +
	"\traw_audio\x18\x06 \x01(\v2\x12.apisyniq.RawAudioH\x00R\brawAudioB\b\n" +
	"\x06packet\"\a\n" +
	"\x05Empty2\xdd\x01\n" +
	"\n" +
	"TTSService\x128\n" +
	"\vUploadAudio\x12\x16.apisyniq.StreamPacket\x1a\x0f.apisyniq.Empty(\x01\x12/\n" +
	"\n" +
	"UploadText\x12\x0e.apisyniq.Text\x1a\x0f.apisyniq.Empty(\x01\x121\n" +
	"\vUploadEvent\x12\x0f.apisyniq.Event\x1a\x0f.apisyniq.Empty(\x01\x121\n" +
	"\vUploadError\x12\x0f.apisyniq.Error\x1a\x0f.apisyniq.Empty(\x01B\x16Z\x14ApiGateway/pkg/protob\x06proto3"

var (
	file_pkg_proto_ApiSyncService_proto_rawDescOnce sync.Once
	file_pkg_proto_ApiSyncService_proto_rawDescData []byte
)

func file_pkg_proto_ApiSyncService_proto_rawDescGZIP() []byte {
	file_pkg_proto_ApiSyncService_proto_rawDescOnce.Do(func() {
		file_pkg_proto_ApiSyncService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_ApiSyncService_proto_rawDesc), len(file_pkg_proto_ApiSyncService_proto_rawDesc)))
	})
	return file_pkg_proto_ApiSyncService_proto_rawDescData
}

var file_pkg_proto_ApiSyncService_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_proto_ApiSyncService_proto_goTypes = []any{
	(*RawAudio)(nil),      // 0: apisyniq.RawAudio
	(*AudioChunk)(nil),    // 1: apisyniq.AudioChunk
	(*IncomingAudio)(nil), // 2: apisyniq.IncomingAudio
	(*Text)(nil),          // 3: apisyniq.Text
	(*Event)(nil),         // 4: apisyniq.Event
	(*Error)(nil),         // 5: apisyniq.Error
	(*StreamPacket)(nil),  // 6: apisyniq.StreamPacket
	(*Empty)(nil),         // 7: apisyniq.Empty
	nil,                   // 8: apisyniq.AudioChunk.OptionsEntry
	nil,                   // 9: apisyniq.IncomingAudio.OptionsEntry
	nil,                   // 10: apisyniq.Text.OptionsEntry
	nil,                   // 11: apisyniq.Event.OptionsEntry
	nil,                   // 12: apisyniq.Error.OptionsEntry
}
var file_pkg_proto_ApiSyncService_proto_depIdxs = []int32{
	8,  // 0: apisyniq.AudioChunk.options:type_name -> apisyniq.AudioChunk.OptionsEntry
	9,  // 1: apisyniq.IncomingAudio.options:type_name -> apisyniq.IncomingAudio.OptionsEntry
	10, // 2: apisyniq.Text.options:type_name -> apisyniq.Text.OptionsEntry
	11, // 3: apisyniq.Event.options:type_name -> apisyniq.Event.OptionsEntry
	12, // 4: apisyniq.Error.options:type_name -> apisyniq.Error.OptionsEntry
	2,  // 5: apisyniq.StreamPacket.audio_in:type_name -> apisyniq.IncomingAudio
	1,  // 6: apisyniq.StreamPacket.audio_out:type_name -> apisyniq.AudioChunk
	3,  // 7: apisyniq.StreamPacket.text:type_name -> apisyniq.Text
	4,  // 8: apisyniq.StreamPacket.event:type_name -> apisyniq.Event
	5,  // 9: apisyniq.StreamPacket.error:type_name -> apisyniq.Error
	0,  // 10: apisyniq.StreamPacket.raw_audio:type_name -> apisyniq.RawAudio
	6,  // 11: apisyniq.TTSService.UploadAudio:input_type -> apisyniq.StreamPacket
	3,  // 12: apisyniq.TTSService.UploadText:input_type -> apisyniq.Text
	4,  // 13: apisyniq.TTSService.UploadEvent:input_type -> apisyniq.Event
	5,  // 14: apisyniq.TTSService.UploadError:input_type -> apisyniq.Error
	7,  // 15: apisyniq.TTSService.UploadAudio:output_type -> apisyniq.Empty
	7,  // 16: apisyniq.TTSService.UploadText:output_type -> apisyniq.Empty
	7,  // 17: apisyniq.TTSService.UploadEvent:output_type -> apisyniq.Empty
	7,  // 18: apisyniq.TTSService.UploadError:output_type -> apisyniq.Empty
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_proto_ApiSyncService_proto_init() }
func file_pkg_proto_ApiSyncService_proto_init() {
	if File_pkg_proto_ApiSyncService_proto != nil {
		return
	}
	file_pkg_proto_ApiSyncService_proto_msgTypes[6].OneofWrappers = []any{
		(*StreamPacket_AudioIn)(nil),
		(*StreamPacket_AudioOut)(nil),
		(*StreamPacket_Text)(nil),
		(*StreamPacket_Event)(nil),
		(*StreamPacket_Error)(nil),
		(*StreamPacket_RawAudio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_ApiSyncService_proto_rawDesc), len(file_pkg_proto_ApiSyncService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_ApiSyncService_proto_goTypes,
		DependencyIndexes: file_pkg_proto_ApiSyncService_proto_depIdxs,
		MessageInfos:      file_pkg_proto_ApiSyncService_proto_msgTypes,
	}.Build()
	File_pkg_proto_ApiSyncService_proto = out.File
	file_pkg_proto_ApiSyncService_proto_goTypes = nil
	file_pkg_proto_ApiSyncService_proto_depIdxs = nil
}
