# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import data_pb2 as data__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.searchMatchesForBoth = channel.unary_unary(
                '/apisyniq.Controller/searchMatchesForBoth',
                request_serializer=data__pb2.query.SerializeToString,
                response_deserializer=data__pb2.InputsAndReturnsMatch.FromString,
                _registered_method=True)
        self.searchMatchesForInputDescription = channel.unary_unary(
                '/apisyniq.Controller/searchMatchesForInputDescription',
                request_serializer=data__pb2.query.SerializeToString,
                response_deserializer=data__pb2.repeatedInput.FromString,
                _registered_method=True)
        self.searchMatchesForReturnDescription = channel.unary_unary(
                '/apisyniq.Controller/searchMatchesForReturnDescription',
                request_serializer=data__pb2.query.SerializeToString,
                response_deserializer=data__pb2.repeatedInput.FromString,
                _registered_method=True)
        self.save = channel.unary_unary(
                '/apisyniq.Controller/save',
                request_serializer=data__pb2.EndpointData.SerializeToString,
                response_deserializer=data__pb2.query.FromString,
                _registered_method=True)


class ControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def searchMatchesForBoth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchMatchesForInputDescription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchMatchesForReturnDescription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'searchMatchesForBoth': grpc.unary_unary_rpc_method_handler(
                    servicer.searchMatchesForBoth,
                    request_deserializer=data__pb2.query.FromString,
                    response_serializer=data__pb2.InputsAndReturnsMatch.SerializeToString,
            ),
            'searchMatchesForInputDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.searchMatchesForInputDescription,
                    request_deserializer=data__pb2.query.FromString,
                    response_serializer=data__pb2.repeatedInput.SerializeToString,
            ),
            'searchMatchesForReturnDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.searchMatchesForReturnDescription,
                    request_deserializer=data__pb2.query.FromString,
                    response_serializer=data__pb2.repeatedInput.SerializeToString,
            ),
            'save': grpc.unary_unary_rpc_method_handler(
                    servicer.save,
                    request_deserializer=data__pb2.EndpointData.FromString,
                    response_serializer=data__pb2.query.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apisyniq.Controller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('apisyniq.Controller', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Controller(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def searchMatchesForBoth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apisyniq.Controller/searchMatchesForBoth',
            data__pb2.query.SerializeToString,
            data__pb2.InputsAndReturnsMatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def searchMatchesForInputDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apisyniq.Controller/searchMatchesForInputDescription',
            data__pb2.query.SerializeToString,
            data__pb2.repeatedInput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def searchMatchesForReturnDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apisyniq.Controller/searchMatchesForReturnDescription',
            data__pb2.query.SerializeToString,
            data__pb2.repeatedInput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apisyniq.Controller/save',
            data__pb2.EndpointData.SerializeToString,
            data__pb2.query.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
